################ COMANDAS

### BUSCAR TODOS AS comandas

GET http://localhost:3048/api/comanda/all

### CADASTRAR Nova comanda

POST http://localhost:3048/api/comanda/create
Content-Type: application/json

{
  "cliente": "Doria"
}


###

DELETE http://localhost:3048/api/comanda/delete
Content-Type: application/json

{
  "id": 1
}

###

GET http://localhost:3048/api/comanda/id/1
Content-Type: application/json

### 

POST  http://localhost:3048/api/comanda/insertProduto
Content-Type: application/json

{
  "comanda": 1,
  "produto": [
    {
      "id": 1,
      "quantidade" : 1,
      "tipo": "Adicionar"
    
    }

  ]
}


###
POST http://localhost:3048/api/comanda/consultProduto
Content-Type: application/json

{
  "comanda": 1

}

###
DELETE http://localhost:3048/api/comanda/deletarProduto
Content-Type: application/json

{
  "comanda": 1,
  "produto": 1

}