name: Continuos Integration 

jobs:
  continuos-integration: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: action/setup-node@v2
        with: 
          node-version: 22.x
      - name: run install, build
        run: |
          npm install --production
          npm install typescript --save-dev
          npm install --save-dev @types/multer
          npm i --save-dev @types/module-alias
          npm run build